Provide dlang-community repo and install dfmt 0.6.*
sociomantic-tsunami/cachalot pull request #37
Opened 2017-10-23 13:38 UTC by stefan-koch-sociomantic

Same as in title.
Adds a configuarion file for the dlang-community apt repo;
and installs dfmt from it

2017-10-23 13:40 UTC, nemanja-boric-sociomantic commented
The second commit should say: "Install dfmt version 0.6.* in dlang image".

2017-10-23 13:40 UTC, nemanja-boric-sociomantic commented
Other than that LGTM

2017-10-23 13:59 UTC, stefan-koch-sociomantic commented
@nemanja-boric-sociomantic changed

2017-10-23 14:00 UTC, nemanja-boric-sociomantic approved these changes

2017-10-23 16:29 UTC, leandro-lucarella-sociomantic requested changes
Please also add simple tests to check if `dfmt` is really installed and the package doesn't get unintentionally upgraded, have a look at:

* https://github.com/sociomantic-tsunami/cachalot/blob/v3.x.x/test/dlang-user
* https://github.com/sociomantic-tsunami/cachalot/blob/v3.x.x/test/dlang-root

2017-10-23 16:29 UTC, leandro-lucarella-sociomantic commented on docker/base
> +echo "deb https://dl.bintray.com/dlang-community/apt $dist prerelease release" \
The prerelease shouldn't be included for now, as we don't have `apt-preferences` properly configured not to pick the prereleases automatically. We should add prereleases at some point, but we need to make sure that they are properly configured.

2017-10-23 16:31 UTC, leandro-lucarella-sociomantic commented
And Travis is not happy, I guess the package is not really in the repos yet?
https://travis-ci.org/sociomantic-tsunami/cachalot/builds/291593128#L2034

2017-10-23 16:34 UTC, leandro-lucarella-sociomantic commented
**SIDE NOTE:** I'm actually considering adding minor verions to cachalot ( ping @mihails-strasuns ), I think putting this in `v4` might be overkill, and making it a patch release also sounds weird. I will have to check if the infra behind this is prepared for minor version releases though.

2017-10-24 11:34 UTC, mihails-strasuns-sociomantic commented
Hm, I don't see any practical reason to go for minors right now. I mean the only reason why we have any versions at all (instead of always using `sociomantictsunami/dlang:latest`) is to avoid silent unexpected upgrades of default packages. It has not direct relation with versioning of those packages and always acts as whole snapshot.

`v4` sounds just fine. Only problem is that if you try to use neptune branch model for it, you will have too many branches at the same time.

2017-10-24 15:18 UTC, stefan-koch-sociomantic commented
I have no idea why this fails actually, the package is in the repo and if I execute the added commands manually in the docker-contrainer it works.

2017-10-24 15:59 UTC, leandro-lucarella-sociomantic commented
> Hm, I don't see any practical reason to go for minors right now. I mean the only reason why we have any versions at all (instead of always using sociomantictsunami/dlang:latest) is to avoid silent unexpected upgrades of default packages. It has not direct relation with versioning of those packages and always acts as whole snapshot.

Well, not entirely, the intention was never really to use `:latest`, as if that's done old branches could stop building if there is a new patch release and the cachalot image changes. The idea is to always use explicit versions. Also, since we now pin versions of the important (external) programs (the internal ubuntu programs are supposed to also only receive bugfix updates), adding a new program doesn't really look like could break anything in the current version (is similar to add symbols in a library, the theoretical possibility to break something exists but is so small that it doesn't make to consider it a breaking change).

2017-10-24 16:01 UTC, leandro-lucarella-sociomantic commented
> v4 sounds just fine. Only problem is that if you try to use neptune branch model for it, you will have too many branches at the same time.

I wouldn't go for a full neptune scheme either, since users are expected to only pin on majors. Or put it another way, I would go for full neptune but I will only keep updating only the latest minor. From the practical experience, there were barely any update to images.

2017-10-26 13:37 UTC, stefan-koch-sociomantic commented
@leandro-lucarella-sociomantic for now I only added the dlang-community repo this should make the pr pass.

2017-10-26 14:33 UTC, leandro-lucarella-sociomantic commented
@stefan-koch-sociomantic https://github.com/sociomantic-tsunami/cachalot/pull/37#pullrequestreview-71247107 still needs to be addressed :)

2017-10-26 14:39 UTC, stefan-koch-sociomantic commented
@leandro-lucarella-sociomantic since this pr does not install dfmt it cannot check it.
I will keep it in mind though

2017-10-26 17:10 UTC, leandro-lucarella-sociomantic commented
Ah, right. But then why isn't provided, is just for initial testing? Because I think cachalot should provide dfmt.

2017-10-27 09:13 UTC, stefan-koch-sociomantic commented
@leandro-lucarella-sociomantic I'd like to do it in two pr's so they'll have a change to all pass testing.

2017-10-27 09:33 UTC, nemanja-boric-sociomantic commented
But you don't know if this one is passing, as your changes are not actually tested.

2017-10-27 09:43 UTC, stefan-koch-sociomantic commented
As a side-note: should we really do all the dlang-specific apt-setup in the base image rather then the dlang image ?

2017-10-27 09:53 UTC, leandro-lucarella-sociomantic commented
> As a side-note: should we really do all the dlang-specific apt-setup in the base image rather then the dlang image ?

No, good catch, the sociomantic bintray repo is there because we have tools there that are not dlang specific (like `git-hub`), but the dlang-specific stuff should go to the dlang image.

2017-10-27 10:11 UTC, stefan-koch-sociomantic commented
> No, good catch, the sociomantic bintray repo is there because we have tools there that are not dlang specific (like git-hub), but the dlang-specific stuff should go to the dlang image.

pr is in progress.

2017-11-03 15:47 UTC, leandro-lucarella-sociomantic commented
Blocked on #38.

2017-11-06 13:18 UTC, stefan-koch-sociomantic commented
@leandro-lucarella-sociomantic just rebased on v4

2017-11-06 16:11 UTC, leandro-lucarella-sociomantic approved these changes

2017-11-06 16:11 UTC, leandro-lucarella-sociomantic commented
Thanks!

2017-11-06 16:11 UTC, merged